//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESLBooksAwardMig2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKLIST
    {
        public int 項次 { get; set; }
        public string 大分類 { get; set; }
        public string 中分類 { get; set; }
        public string 獨立編號 { get; set; }
        public string 圖檔名 { get; set; }
        public string ProductGuid { get; set; }
        public int 順序 { get; set; }
        public string 屬性 { get; set; }
        public string 推薦書籍 { get; set; }
        public string ISBN { get; set; }
        public string MCH { get; set; }
        public string 分類 { get; set; }
        public System.DateTime 出版日期 { get; set; }
        public string 出版社 { get; set; }
        public string 推薦單位 { get; set; }
        public string 推薦總編 { get; set; }
        public string 職銜 { get; set; }
        public string 總編推薦文 { get; set; }
        public string 推薦職人店別 { get; set; }
        public string 職人姓名 { get; set; }
        public string 職人推薦文 { get; set; }
        public string 推薦作者 { get; set; }
        public string Tag { get; set; }
        public string 書落 { get; set; }
    }
}
